name: JIRA

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write
env:
  PROJECT_KEY: GFMC
  JIRA_EXECUTION_ID: GFMC-24435

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests

    steps:
      - name: Checking out Github Repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update APT packages
        run: |
          sudo apt update
          sudo apt install --only-upgrade openssl
          sudo apt install firefox
          
          

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade robotframework-selenium2library
          python -m pip install -U robotframework-jsonlibrary
          python -m pip install robotframework-requests
          python -m pip install jsonpath-ng
          python -m pip install jsonpath-rw
          python -m pip install robotframework-seleniumlibrary
          python -m pip install collection
          python -m pip install robotframework-jsonlibrary
          pip install robotframework-stacktrace
          python -m pip install pillow
          pip install robotframework==6.0.2
          pip install jproperties
          pip install -r requirements_local.txt 
          echo "PATH Variable"
          echo "$PATH"
          echo "current working directory"
          pwd
          echo "list directories"
          ls -a
      - name: Download geckodriver and Run test case
        run: |
          export GV=v0.32.2
          wget "https://github.com/mozilla/geckodriver/releases/download/$GV/geckodriver-$GV-linux64.tar.gz"
          tar xvzf geckodriver-$GV-linux64.tar.gz
          chmod +x geckodriver
          sudo cp geckodriver /usr/local/bin/
          echo $PATH
          echo "PATH Variable"
          echo "$PATH"
          echo "current working directory"
          pwd
          echo "list directories"
          ls -a
          echo "Executing Test cases"
          mkdir output
          chmod 777 output
          cd output
          robot /home/runner/work/CumulusCI_First/CumulusCI_First/robot/CumulusCI_First/tests/


      - name: Jira From Shell Script
        if: always()
        run: |
          chmod +x /home/runner/work/CumulusCI_First/CumulusCI_First/jira.sh
          /home/runner/work/CumulusCI_First/CumulusCI_First/jira.sh

#      - name: Submit results to Xray
#        if: always()
#        env:
#          JIRA_SERVER_URL: ${{ secrets.JIRA_SERVER_URL }}
#          JIRA_USERNAME: ${{ secrets.JIRA_USER_NAME }}
#          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
#        run: 'curl -H "Content-Type: multipart/form-data" -u $JIRA_USERNAME:$JIRA_PASSWORD -F "file=@/home/runner/work/CumulusCI_First/CumulusCI_First/output/output.xml" "$JIRA_SERVER_URL/rest/raven/2.0/import/execution/robot?projectKey=${PROJECT_KEY}&testExecKey=${JIRA_EXECUTION_ID}"'

          

      - name: Final Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Output Report
          path: /home/runner/work/CumulusCI_First/CumulusCI_First/output




