name: robot_test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests

    steps:
      - name: Checking out Github Repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update APT packages
        run: |
          sudo apt update
          sudo apt install --only-upgrade openssl
          sudo apt install firefox
          
#      - name: Download geckodriver
#        run: |
#          wget https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux64.tar.gz
#          sudo sh -c 'tar -x geckodriver -zf geckodriver-v0.32.2-linux64.tar.gz -O > /usr/bin/geckodriver'
#          sudo chmod +x /usr/bin/geckodriver
#          rm geckodriver-v0.32.2-linux64.tar.gz
#          export PATH=$PATH:/usr/bin/geckodriver
#          echo $PATH

      - name: Install python dependencies and Run Robot framework
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade robotframework-selenium2library
          python -m pip install -U robotframework-jsonlibrary
          python -m pip install robotframework-requests
          python -m pip install jsonpath-ng
          python -m pip install jsonpath-rw
          python -m pip install robotframework-seleniumlibrary
          python -m pip install collection
          python -m pip install robotframework-jsonlibrary
          pip install robotframework-stacktrace
          python -m pip install pillow
          pip install robotframework==6.0.2
          echo "PATH Variable"
          echo "$PATH"
          echo "current working directory"
          pwd
          echo "list directories"
          ls -a
#          echo "Executing Test cases"
#          cd robot
#          cd CumulusCI_First
#          cd tests
#          cd /usr/bin/firefox
#          robot GFMC10649.robot
#          robot GFMC11061.robot


      - name: Download geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux64.tar.gz
          sudo sh -c 'tar -x geckodriver -zf geckodriver-v0.32.2-linux64.tar.gz -O > /usr/bin/geckodriver'
          sudo chmod +x /usr/bin/geckodriver
          rm geckodriver-v0.32.2-linux64.tar.gz
          export PATH=$PATH:/usr/bin/geckodriver
          echo $PATH

      - name: Run Test
        run: |
          echo "PATH Variable"
          echo "$PATH"
          echo "current working directory"
          pwd
          echo "list directories"
          ls -a
          echo "Executing Test cases"
          cd robot
          cd CumulusCI_First
          cd tests
#          cd /usr/bin/firefox
          robot GFMC10649.robot
          robot GFMC11061.robot

          
     
      
